### ISSUE TITLE
Update entire project to new vercel

### ISSUE THREAD

**Issue by ohager** [ohager/burst-account-activator#6]
Due to some weirdnesses probably related to caching from the network and the deprecated deployment mechanism, it is time to update the project using most recent deployment mechanism. Then we have support per env vars directly in vercel.

Additionally, I need to add some decent logging and also the possibility to track which app is calling the service. Furthermore let's see to add OAS and Swagger UI.

**Comment by ohager** [comment]
oops

**Comment by map1336** [comment]
![image](https://user-images.githubusercontent.com/35440957/132969827-84f77f6f-d5ff-4c68-a0e1-609d4bc7a951.png)
@ohager It seems the app is already hosted on vercel!

**Comment by ohager** [comment]
done
